version: '3.8'

services:
  backend:
    build: ./backend
    container_name: skillmatch-backend
    environment:
      - DATABASE_URL=postgresql://skillmatch_user:skillmatch_password@postgres:5432/skillmatch
      - SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - ALLOWED_HOSTS=*
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - skillmatch-network

  frontend:
    build: ./frontend
    container_name: skillmatch-frontend
    environment:
      - REACT_APP_API_URL=http://localhost/api
    networks:
      - skillmatch-network

  postgres:
    image: postgres:15-alpine
    container_name: skillmatch-postgres
    environment:
      - POSTGRES_DB=skillmatch
      - POSTGRES_USER=skillmatch_user
      - POSTGRES_PASSWORD=skillmatch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skillmatch-network

  nginx:
    image: nginx:alpine
    container_name: skillmatch-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - skillmatch-network

volumes:
  postgres_data:

networks:
  skillmatch-network:
    driver: bridge
