version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://skillmatch_user:skillmatch_password@postgres:5432/skillmatch
      - SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - ALLOWED_HOSTS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - skillmatch-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - skillmatch-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=skillmatch
      - POSTGRES_USER=skillmatch_user
      - POSTGRES_PASSWORD=skillmatch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - skillmatch-network

volumes:
  postgres_data:

networks:
  skillmatch-network:
    driver: bridge
